### ISSUE TITLE
Could you please provide the processed data and the fine-tuned model used for prediction? Thanks.

### ISSUE THREAD

**Issue by dingjun7** [SparkJiao/MERIt#1]

**Comment by SparkJiao** [comment]
Hi, thanks for your question.

For the processed data for pre-training, i.e., the Wikipedia corpus, the link can be found in README.

The data for fine-tuning can be processed by yourself since the datasets are small. We have released the code for processing. We will update README with the details of fine-tuning.

We will also upload the fine-tuned models as soon as possible.

**Comment by SparkJiao** [comment]
Hi,

We have update the details about the configs we used for fine-tuning. We are sorry that we will not release the fine-tuned models since the results can be easily reproduced by yourself with the provided configs. 

There are too many fine-tuned models and it can be difficult for us to release them all.

If you have more questions, feel free to re-open this issue.
